### ISSUE TITLE
Add MLLM-Bench results

### ISSUE THREAD

**Issue by g-h-chen** [xverse-ai/XVERSE-V-13B#3]
Hi, congrats on your great work! Do you consider adding [MLLM-Bench](https://github.com/FreedomIntelligence/MLLM-Bench), which is a benchmark that tests the generation ability of open-ended questions.

Thanks!

**Comment by Zoisaang** [comment]
Sorry, we don't have a plan to test on MLLM-Bench now, but maybe later on.
